//
// Created by hsk on 22-12-17.
//

#ifndef WINDOW_INFO_EXTRA_XORG_EXTENSION_EXTENSION_H
#define WINDOW_INFO_EXTRA_XORG_EXTENSION_EXTENSION_H

void wi_ext_init();

#endif //WINDOW_INFO_EXTRA_XORG_EXTENSION_EXTENSION_H
